minimal ci setup
khionu/bitstrings-rs pull request #2
Opened 2024-03-31 21:07 UTC by Licenser

add ci tasks for clippy, fmt and test

2024-04-01 19:23 UTC, khionu requested changes

2024-04-01 19:23 UTC, khionu commented on rust-toolchain.toml
> +components = ["rust-src", "rust-analyzer", "rustfmt", "clippy"]
The `default` profile should already include these?

2024-04-01 19:24 UTC, khionu commented on rust-toolchain.toml
> +components = ["rust-src", "rust-analyzer", "rustfmt", "clippy"]
https://rust-lang.github.io/rustup/concepts/profiles.html

2024-04-02 06:59 UTC, Licenser commented on rust-toolchain.toml
> +components = ["rust-src", "rust-analyzer", "rustfmt", "clippy"]
ah yes, you are right

2024-04-02 19:54 UTC, khionu approved these changes

2024-04-03 06:24 UTC, merged